### ISSUE TITLE
🚨 v0.3.x Roadmap

### ISSUE THREAD

**Issue by fudiwei** [usual2970/certimate#355]
> [!WARNING]
> 0.3.x 版本目前还没有稳定，请勿在生产环境中使用。

v0.3.x 是一个不与 v0.1.x ~ v0.2.x 兼容的大版本。

**路线图**：

- [x] 使用工作流形式组织证书申请流程。
- [ ] 支持在 ACME DNS-01 认证过程中手动添加 TXT 解析记录。
- [ ] 支持设置多个独立的通知器。
- [ ] 支持手动下载证书。
- [ ] 支持自定义过期检测时间。
- [ ] 支持更多的 DNS 服务商和部署方式。
- [ ] 完善文档。
- [ ] _TODO..._

本路线图仅代表 v0.3.x 整个生命周期过程中的工作计划，但不代表首个 v0.3.0 正式版本发布时会全部完成。

P.S. 此 Issue 仅用于公示信息，请勿在此 Issue 下反馈 Bug 或 Feature Request。如有需要请单独开启 Issue。

---

> [!WARNING]
> Version 0.3.x is currently unstable and should **not** be used in production environments.

v0.3.x is a major version that is **not** backward compatible with v0.1.x ~ v0.2.x.

**Roadmap**:

- [x] Organize the certificate request process using workflows.
- [ ] Support adding TXT records manually during ACME DNS-01 verification.
- [ ] Support configuring multiple independent notifiers.
- [ ] Support downloading certificate manually.
- [ ] Support custom expiration checking time.
- [ ] Support more DNS providers and deployment targets.
- [ ] Improve documentation.
- [ ] _TODO..._

This roadmap represents the planned things for the entire v0.3.x life-cycle, but it does not guarantee that all of these will be available in the first stable v0.3.0 release.

P.S. This issue is intended for public information only. Please do not report bugs or feature requests here. For those, please open a separate issue.

**Comment by meilonme** [comment]
试了一下0.3版的, 整体使用体验比0.2版好了不少, 但是还有两点问题
1. 中间环节执行失败会导致整个流程结束, 但是某些节点的失败其实是不影响整体流程的, 比如我在申请成功后发送一个通知, 不管通知成功与否, 都不影响后续的部署的, 因此是否可以节点上增加一个参数, 控制失败是否结束流程;
2. 添加分支是否可以分成"失败分支"和"成功分支", 上一个节点执行失败走"失败分支", 成功则走"成功分支", 如此可以自行控制某个环节成功了如何处理, 失败了如何处理, 比如根据处理结果发送不同的通知渠道, 或者失败时执行一些补救措施
